# GitHub FUNDING.yml
github: brazilianscriptguy
patreon: brazilianscriptguy
custom: 
  - "https://www.buymeacoffee.com/brazilianscriptguy"
  - "https://ko-fi.com/brazilianscriptguy"
  - "https://gofund.me/4599d3e6"
