# GitHub FUNDING.yml
github: brazilianscriptguy
patreon: brazilianscriptguy
custom: 
  - "https://www.paypal.com/donate?hosted_button_id=YOUR_PAYPAL_BUTTON_ID"
  - "https://www.buymeacoffee.com/brazilianscriptguy"
  - "https://ko-fi.com/brazilianscriptguy"
