server:
  port: 8080

spring:
  ldap:
    urls: ldap://ldap.headq.scriptguy:3268
    base: dc=HEADQ,dc=SCRIPTGUY
    username: ad-sso-authentication@headq
    password: ${LDAP_PASSWORD}
    user-search-filter: (sAMAccountName={0})
    group-search-filter: (member={0})
